### ISSUE TITLE
Not able to run make from cd-build directory

### ISSUE THREAD

**Issue by shrin18** [anastas/gr-cdma#33]
/usr/local/include/gnuradio/basic_block.h:94:17: error: ‘rpcbasic_sptr’ was not declared in this scope
     std::vector<rpcbasic_sptr> d_rpc_vars; // container for all RPC variables
                 ^~~~~~~~~~~~~
/usr/local/include/gnuradio/basic_block.h:94:17: note: suggested alternative: ‘top_block_sptr’
     std::vector<rpcbasic_sptr> d_rpc_vars; // container for all RPC variables
                 ^~~~~~~~~~~~~
                 top_block_sptr
/usr/local/include/gnuradio/basic_block.h:94:30: error: template argument 1 is invalid
     std::vector<rpcbasic_sptr> d_rpc_vars; // container for all RPC variables
                              ^
/usr/local/include/gnuradio/basic_block.h:94:30: error: template argument 2 is invalid
lib/CMakeFiles/gnuradio-cdma.dir/build.make:86: recipe for target 'lib/CMakeFiles/gnuradio-cdma.dir/packet_headerparser_b2_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-cdma.dir/packet_headerparser_b2_impl.cc.o] Error 1
CMakeFiles/Makefile2:174: recipe for target 'lib/CMakeFiles/gnuradio-cdma.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-cdma.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Could you suggest us with some steps to run make so that we could proceed with the cdma implementation ? Thanks in advance.

**Comment by anastas** [comment]
I will need much more than that in order to help you.

Have you followed the directions in README?

can you show me evidence of the directory you have put the code and the cdma_partameters.py file.

What gnuradio version you have installed etc.

The more info you give me the better.

**Comment by shrin18** [comment]
Yes I have followed the instructions. 

gnuradio version: 3.7.11

Code for cdma_parameters.py in the attached file

-->
![ss1](https://user-images.githubusercontent.com/23298265/64793996-2ed6c980-d57c-11e9-8ac0-c116106e1032.png)

**Comment by anastas** [comment]
can you first try 

remove all files from the build directory
and then run:

cmake -DENABLE_DOXYGEN=OFF "PATH TO YOUR gr-cdma TRUNK"

in case there are issues with the documentation...

can you post the output of the cmake

**Comment by shrin18** [comment]
![anastas1](https://user-images.githubusercontent.com/23298265/64855000-313e2f80-d61f-11e9-991d-ef4b6e12a803.png)

**Comment by shrin18** [comment]
I have tried it from a different computer where the trunk directory is as follows:

/home/ubuntu/gnuradio/gr-cdma

**Comment by anastas** [comment]
it is obvious that there is a problem with DOXYGEN that generates the documentation. That's why I asked you in the previous post to configure without documentation generation.

It does not seem that you have done what I asked you in my previous post!
If you do not follow the instruction in the README file I cannot help you.
They are quite simple.

0) What is your "trunk" directory and what is your "build" directory? (it seems you have both the same for some reason...)
1) remove all files from the "build" directory
2) cmake -DENABLE_DOXYGEN=OFF "PATH TO YOUR gr-cdma TRUNK"
3)  post the output of the ENTIRE process:
cd-ing in your build directory, running cmake, running make etc.
 
BTW: please do not post screenshots! You can cut and paste the contents of the terminal as text!

Unless you do all of the above in the next post I will close it.

**Comment by shrin18** [comment]
Fixed it.
